export const OPERATION_RESOURCE = 'OPERATION';
export const OPERATION_DOCUMENT_RESOURCE = 'OPERATION_DOCUMENT';
export const OPERATION_PHOTO_RESOURCE = 'OPERATION_PHOTO';

export const OPERATION_AUDIT_ACTIONS = {
  OPERATION_CREATED: 'OPERATION_CREATED',
  OPERATION_DELEGATED: 'OPERATION_DELEGATED',
  OPERATION_UPDATED: 'OPERATION_UPDATED',
  OPERATION_CANCELED: 'OPERATION_CANCELED',
  OPERATION_REACTIVATED: 'OPERATION_REACTIVATED',
  OPERATION_DELETED: 'OPERATION_DELETED',
  OPERATION_APPROVED: 'OPERATION_APPROVED',
  OPERATION_DOCUMENT_CREATED: 'OPERATION_DOCUMENT_CREATED',
  OPERATION_PHOTO_UPLOADED: 'OPERATION_PHOTO_UPLOADED',
  OPERATION_PHOTO_CAPTION_UPDATED: 'OPERATION_PHOTO_CAPTION_UPDATED',
  OPERATION_PHOTO_DELETED: 'OPERATION_PHOTO_DELETED',
} as const;

export const MAX_OPERATION_PHOTOS = 16;
export const MAX_OPERATION_PHOTO_SIZE_BYTES = 5 * 1024 * 1024;
export const OPERATION_PHOTO_MIME_TYPES = ['image/png', 'image/jpeg'] as const;
export const MAX_OPERATION_SIGNATURE_SIZE_BYTES = 2 * 1024 * 1024;
export const OPERATION_SIGNATURE_MIME_TYPES = ['image/png', 'image/jpeg'] as const;

/** Document number prefixes per produced document type. */
export const OPERATION_DOCUMENT_PREFIX: Record<string, string> = {
  BUDGET: 'ORC',
  WORK_ORDER: 'OS',
  QUOTE: 'ORC',
  RECEIPT: 'REC',
  REPORT: 'REL',
  TECHNICAL_REPORT: 'RVT',
  TECHNICAL_OPINION: 'LDO',
  PMOC: 'PMOC',
};

/** Format an Operation sequential number into a zero-padded document code. */
export function formatDocumentNumber(prefix: string, sequential: number): string {
  return `${prefix}-${String(sequential).padStart(6, '0')}`;
}
