"use client";

import { useMemo, useState } from "react";
import { CalendarClock, Headphones, Loader2, Wrench } from "lucide-react";
import { FilterBar } from "@erp/ui/filter-bar";
import { EmptyState } from "@erp/ui/empty-state";
import { StatusChip } from "@erp/ui/status-chip";
import { Pagination } from "@platform/components/pagination";
import { OperationCreationDrawer } from "@platform/components/operation-creation-drawer";
import { serviceRequestsApi, useQuery, type CreateOperationPayload, type ServiceRequest, type ServiceRequestStatus, type ServiceRequestType } from "@erp/api";

const statusLabel: Record<ServiceRequestStatus, string> = { OPEN: "Aberto", IN_REVIEW: "Em análise", SCHEDULED: "Agendado", CLOSED: "Concluído", CANCELED: "Cancelado" };
const typeLabel: Record<ServiceRequestType, string> = { WORK_ORDER: "OS", RVT: "RVT", TECHNICAL_REPORT: "Laudo Técnico" };
const typeDocument = { WORK_ORDER: "WORK_ORDER", RVT: "REPORT", TECHNICAL_REPORT: "TECHNICAL_REPORT" } as const;

export default function ServiceRequestsPage() {
  const [page, setPage] = useState(1); const [limit, setLimit] = useState(20);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState<ServiceRequestStatus | "">(""); const [type, setType] = useState<ServiceRequestType | "">("");
  const [selected, setSelected] = useState<ServiceRequest | null>(null); const [creating, setCreating] = useState(false);
  const query = useQuery((signal) => serviceRequestsApi.listRequests({ page, limit, search: search || undefined, status: status || undefined, type: type || undefined, signal }), [page, limit, search, status, type], { refetchInterval: 30000 });
  const prefill = useMemo<Partial<CreateOperationPayload> | undefined>(() => selected ? ({ customerId: selected.customerId, addressId: selected.addressId, equipmentId: selected.equipments[0]?.equipment.id, inspectedEquipments: selected.equipments.map(({ equipment }) => ({ equipmentId: equipment.id, sector: equipment.sector || "Não informado", manufacturer: equipment.manufacturer, model: equipment.model, capacity: equipment.capacity })), type: "CORRETIVA", documentType: typeDocument[selected.type], reportedIssue: selected.description, observations: [`Origem: chamado #${String(selected.number).padStart(6, "0")}`, selected.contactName ? `Contato: ${selected.contactName}${selected.contactPhone ? ` · ${selected.contactPhone}` : ""}` : "", selected.preferredAt ? `Preferência do cliente: ${new Date(selected.preferredAt).toLocaleString("pt-BR")}` : ""].filter(Boolean).join("\n"), scheduledFor: selected.preferredAt }) : undefined, [selected]);

  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--color-primary)]">Gestão</p><h1 className="mt-1 text-2xl font-bold">Chamados</h1><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">Solicitações abertas pelos clientes, da triagem à criação da operação.</p></div>
    <FilterBar search={search} onSearch={(value) => { setSearch(value); setPage(1); }} searchPlaceholder="Buscar cliente, assunto ou descrição…"><select value={status} onChange={(e) => { setStatus(e.target.value as ServiceRequestStatus | ""); setPage(1); }} className="input h-9 w-auto"><option value="">Todos os status</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={type} onChange={(e) => { setType(e.target.value as ServiceRequestType | ""); setPage(1); }} className="input h-9 w-auto"><option value="">Todos os tipos</option>{Object.entries(typeLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></FilterBar>
    {query.loading && !query.data ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[var(--color-primary)]" /></div> : !query.data?.items.length ? <EmptyState icon={Headphones} title="Nenhum chamado encontrado" description="Os chamados abertos no portal do cliente aparecerão aqui." /> : <div className="overflow-hidden rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-card)]"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-[var(--color-border)] bg-[var(--color-muted)] text-xs text-[var(--color-muted-foreground)]"><tr><th className="px-4 py-3">Chamado</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Abertura</th><th className="px-4 py-3"></th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id} className="border-b border-[var(--color-border)] last:border-0 hover:bg-[var(--color-muted)]/50"><td className="px-4 py-3"><p className="font-medium">#{String(item.number).padStart(6, "0")} · {item.subject}</p><p className="max-w-sm truncate text-xs text-[var(--color-muted-foreground)]">{item.description}</p></td><td className="px-4 py-3">{item.customer.tradeName || item.customer.name}</td><td className="px-4 py-3">{typeLabel[item.type]}</td><td className="px-4 py-3"><StatusChip tone={item.status === "CLOSED" ? "success" : item.status === "CANCELED" ? "danger" : "info"}>{statusLabel[item.status]}</StatusChip></td><td className="px-4 py-3 whitespace-nowrap">{new Date(item.createdAt).toLocaleDateString("pt-BR")}</td><td className="px-4 py-3 text-right"><button onClick={() => setSelected(item)} className="rounded-[var(--radius-md)] border border-[var(--color-border)] px-3 py-1.5 text-xs font-medium hover:bg-[var(--color-card)]">Gerenciar</button></td></tr>)}</tbody></table></div><div className="border-t border-[var(--color-border)] p-4"><Pagination pagination={query.data.pagination} onPageChange={setPage} onPageSizeChange={(value) => { setLimit(value); setPage(1); }} /></div></div>}
    {selected && <RequestDrawer request={selected} onClose={() => setSelected(null)} onChanged={() => { query.refetch(); setSelected(null); }} onCreate={() => setCreating(true)} />}
    <OperationCreationDrawer open={creating} mode="operation" onClose={() => setCreating(false)} initialValues={prefill} lockCustomer submitLabel="Criar operação do chamado" contextNotice={selected ? `Os dados foram extraídos do chamado #${String(selected.number).padStart(6, "0")}. Revise e delegue a um operador.` : undefined} submitOperation={(payload) => serviceRequestsApi.createOperation(selected!.id, payload)} onCreated={() => { setCreating(false); setSelected(null); query.refetch(); }} />
  </div>;
}

function RequestDrawer({ request, onClose, onChanged, onCreate }: { request: ServiceRequest; onClose: () => void; onChanged: () => void; onCreate: () => void }) {
  const [status, setStatus] = useState<ServiceRequestStatus>(request.status); const [notes, setNotes] = useState(request.internalNotes || ""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); await serviceRequestsApi.updateRequest(request.id, { status, internalNotes: notes }); onChanged(); }
  return <div className="fixed inset-0 z-40 flex justify-end bg-black/35" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="h-full w-full max-w-xl overflow-y-auto bg-[var(--color-card)] p-6 shadow-[var(--shadow-floating)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-[var(--color-primary)]">Chamado #{String(request.number).padStart(6, "0")}</p><h2 className="mt-1 text-xl font-bold">{request.subject}</h2><p className="text-sm text-[var(--color-muted-foreground)]">{request.customer.tradeName || request.customer.name} · {typeLabel[request.type]}</p></div><button onClick={onClose} className="p-2 text-xl">×</button></div><div className="mt-6 space-y-5"><section className="rounded-[var(--radius-lg)] border border-[var(--color-border)] p-4"><h3 className="text-sm font-semibold">Solicitação</h3><p className="mt-2 whitespace-pre-wrap text-sm text-[var(--color-muted-foreground)]">{request.description}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Info label="Contato" value={[request.contactName, request.contactPhone].filter(Boolean).join(" · ") || "—"} /><Info label="Preferência" value={request.preferredAt ? new Date(request.preferredAt).toLocaleString("pt-BR") : "—"} /><Info label="Endereço" value={request.address ? `${request.address.name} · ${request.address.street}, ${request.address.number}` : "—"} /><Info label="Equipamentos" value={request.equipments.map(({ equipment }) => equipment.name).join(", ") || "Nenhum selecionado"} /></dl></section><label className="grid gap-1.5 text-sm font-medium">Status<select className="input" value={status} onChange={(e) => setStatus(e.target.value as ServiceRequestStatus)}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Notas internas<textarea className="input h-auto py-3" rows={4} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Visível somente para a gestão" /></label><div className="flex flex-wrap justify-end gap-2"><button onClick={() => void save()} disabled={saving} className="h-10 rounded-[var(--radius-md)] border border-[var(--color-border)] px-4 text-sm">{saving ? "Salvando…" : "Salvar triagem"}</button>{!request.operation && request.status !== "CANCELED" && <button onClick={onCreate} className="inline-flex h-10 items-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-primary)] px-4 text-sm font-semibold text-[var(--color-primary-foreground)]"><Wrench className="h-4 w-4" /> Criar operação</button>}{request.operation && <div className="flex items-center gap-2 rounded-[var(--radius-md)] bg-green-500/10 px-3 text-sm text-green-700"><CalendarClock className="h-4 w-4" /> Operação #{String(request.operation.number).padStart(6, "0")}</div>}</div></div></aside></div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[var(--color-muted-foreground)]">{label}</dt><dd className="mt-0.5 break-words">{value}</dd></div>; }
