'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ClipboardList, LogOut, MapPin, MonitorCog, Plus, Search, TicketCheck, Wrench } from 'lucide-react';
import { BrandLogo } from '@erp/ui/brand';
import { MultiSelect } from '@erp/ui/multi-select';
import { Drawer } from '@erp/ui/drawer';
import { EmptyState } from '@erp/ui/empty-state';
import { ErrorState } from '@erp/ui/states';
import { SkeletonList } from '@erp/ui/skeletons';
import { useCustomerAuth } from '@erp/ui/auth/customer-auth-provider';
import { ApiClientError, customerPortalApi, useQuery, type CustomerPortalEquipment, type CustomerPortalOperation, type CustomerServiceTicket, type DocumentTemplateType } from '@erp/api';
import { formatDate, formatDateTime } from '@erp/utils';

type PortalTab = 'overview' | 'services' | 'equipments' | 'tickets';
const DOCUMENT_LABEL: Record<DocumentTemplateType, string> = { WORK_ORDER: 'Ordem de Serviço', TECHNICAL_REPORT: 'Visita Técnica', TECHNICAL_OPINION: 'Laudo Técnico', PMOC: 'PMOC', BUDGET: 'Orçamento', QUOTE: 'Cotação', RECEIPT: 'Recibo', REPORT: 'Relatório' };
const STATUS_LABEL: Record<string, string> = { DRAFT: 'Rascunho', PENDING: 'Pendente', IN_PROGRESS: 'Em atendimento', REVIEW: 'Em revisão', COMPLETED: 'Concluído', CANCELED: 'Cancelado', OPEN: 'Aberto', IN_REVIEW: 'Em análise', OPERATION_CREATED: 'Atendimento criado', CLOSED: 'Encerrado' };
const TICKET_TYPE_OPTIONS: Array<{ value: DocumentTemplateType; label: string }> = [
  { value: 'WORK_ORDER', label: 'Ordem de Serviço' },
  { value: 'TECHNICAL_REPORT', label: 'Relatório de Visita Técnica' },
  { value: 'TECHNICAL_OPINION', label: 'Laudo Técnico' },
];

export default function CustomerPortalPage() {
  const { session, logout } = useCustomerAuth();
  const router = useRouter();
  const [tab, setTab] = useState<PortalTab>('overview');
  const [ticketOpen, setTicketOpen] = useState(false);
  const [ticketVersion, setTicketVersion] = useState(0);
  if (!session) return null;
  async function exit() { await logout(); router.replace('/customer/login'); }
  const tabs: Array<[PortalTab, string]> = [['overview', 'Visão geral'], ['services', 'Serviços e histórico'], ['equipments', 'Equipamentos'], ['tickets', 'Chamados']];
  return <div className="min-h-dvh bg-[var(--color-background)] text-[var(--color-foreground)]">
    <header className="sticky top-0 z-30 border-b border-[var(--color-border)] bg-[var(--color-card)]/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-3 sm:px-6"><BrandLogo height={36}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{session.customer.tradeName || session.customer.name}</p><p className="text-caption">Portal do cliente</p></div><button type="button" onClick={() => void exit()} className="btn-secondary"><LogOut className="h-4 w-4"/><span className="hidden sm:inline">Sair</span></button></div>
    </header>
    <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:py-8">
      <section className="flex flex-col gap-4 rounded-2xl border border-[var(--color-border)] bg-gradient-to-br from-[var(--color-primary)]/10 via-[var(--color-card)] to-[var(--color-card)] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--color-primary)]">Área do cliente</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Olá, {session.account.name}</h1><p className="mt-2 max-w-2xl text-sm text-[var(--color-muted-foreground)]">Consulte seu histórico operacional, equipamentos e acompanhe as solicitações enviadas à equipe.</p></div><button type="button" className="btn-primary h-11 shrink-0" onClick={() => setTicketOpen(true)}><Plus className="h-4 w-4"/>Abrir chamado</button></section>
      <nav className="flex gap-1 overflow-x-auto border-b border-[var(--color-border)]" aria-label="Áreas do portal">{tabs.map(([value,label]) => <button key={value} type="button" onClick={() => setTab(value)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium ${tab === value ? 'border-[var(--color-primary)] text-[var(--color-primary)]' : 'border-transparent text-[var(--color-muted-foreground)]'}`}>{label}</button>)}</nav>
      {tab === 'overview' && <CustomerOverview onOpenTicket={() => setTicketOpen(true)}/>} 
      {tab === 'services' && <CustomerServices/>}
      {tab === 'equipments' && <CustomerEquipments/>}
      {tab === 'tickets' && <CustomerTickets onOpenTicket={() => setTicketOpen(true)} version={ticketVersion}/>} 
    </main>
    <TicketDrawer open={ticketOpen} onClose={() => setTicketOpen(false)} onCreated={() => setTicketVersion((value) => value + 1)}/>
  </div>;
}

function CustomerOverview({ onOpenTicket }: { onOpenTicket: () => void }) {
  const { session } = useCustomerAuth();
  const operations = useQuery((signal) => customerPortalApi.listOperations({ page: 1, limit: 5, signal }), []);
  const equipments = useQuery((signal) => customerPortalApi.listEquipments(signal), []);
  const tickets = useQuery((signal) => customerPortalApi.listMyTickets({ page: 1, limit: 5, signal }), []);
  if (!session) return null;
  const completed = operations.data?.items.filter((item) => item.status === 'COMPLETED').length ?? 0;
  const openTickets = tickets.data?.items.filter((item) => item.status === 'OPEN' || item.status === 'IN_REVIEW').length ?? 0;
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={ClipboardList} label="Atendimentos recentes" value={String(operations.data?.pagination.total ?? 0)}/><Metric icon={TicketCheck} label="Concluídos nesta página" value={String(completed)}/><Metric icon={MonitorCog} label="Equipamentos ativos" value={String(equipments.data?.length ?? 0)}/><Metric icon={Wrench} label="Chamados em aberto" value={String(openTickets)}/></div><div className="grid gap-4 lg:grid-cols-[1fr_1.35fr]"><section className="portal-card"><h2 className="font-semibold">Dados cadastrais</h2><dl className="mt-4 space-y-3 text-sm"><Data label={session.customer.type === 'COMPANY' ? 'Razão social' : 'Nome'} value={session.customer.name}/><Data label="Nome fantasia" value={session.customer.tradeName}/><Data label={session.customer.type === 'COMPANY' ? 'CNPJ' : 'CPF'} value={session.customer.cnpj || session.customer.cpf}/><Data label="E-mail" value={session.customer.email}/><Data label="Telefone" value={session.customer.phone}/></dl><h3 className="mt-6 text-sm font-semibold">Endereços</h3><div className="mt-3 space-y-2">{session.customer.addresses.map((address) => <div key={address.id} className="rounded-lg bg-[var(--color-muted)]/50 p-3 text-sm"><strong>{address.name}</strong><p className="text-caption">{address.street}, {address.number} · {address.city}/{address.state}</p></div>)}</div></section><section className="portal-card"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Últimos atendimentos</h2><p className="text-caption">Movimentações operacionais mais recentes.</p></div><button onClick={onOpenTicket} className="btn-secondary"><Plus className="h-4 w-4"/>Novo</button></div>{operations.loading ? <SkeletonList rows={4}/> : operations.data?.items.length ? <div className="mt-3 divide-y divide-[var(--color-border)]">{operations.data.items.map((item) => <OperationRow key={item.id} item={item}/>)}</div> : <EmptyState icon={ClipboardList} title="Sem atendimentos" description="Ainda não há serviços registrados."/>}</section></div></div>;
}

function CustomerServices() {
  const [page,setPage] = useState(1); const [search,setSearch] = useState(''); const [selected,setSelected] = useState<CustomerPortalOperation|null>(null);
  const list = useQuery((signal) => customerPortalApi.listOperations({ page, limit: 15, search, signal }), [page,search]);
  return <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">Serviços e histórico</h2><p className="text-caption">Ordens de Serviço, RVTs, laudos e execuções vinculadas ao seu cadastro.</p></div><label className="relative block sm:w-80"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--color-muted-foreground)]"/><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Buscar no histórico" className="input w-full pl-9"/></label></div>{list.loading && !list.data ? <SkeletonList rows={6}/> : list.error ? <ErrorState error={list.error} onRetry={list.refetch}/> : list.data?.items.length ? <div className="grid gap-3">{list.data.items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="portal-card text-left transition hover:border-[var(--color-primary)]/50"><OperationRow item={item}/></button>)}</div> : <EmptyState icon={ClipboardList} title="Nenhum serviço encontrado" description="Altere a busca ou aguarde o primeiro atendimento."/>}{list.data && list.data.pagination.totalPages > 1 && <SimplePager page={page} total={list.data.pagination.totalPages} onChange={setPage}/>}<OperationDrawer item={selected} onClose={() => setSelected(null)}/></section>;
}

function CustomerEquipments() {
  const [selected,setSelected] = useState<CustomerPortalEquipment|null>(null);
  const list = useQuery((signal) => customerPortalApi.listEquipments(signal), []);
  return <section className="space-y-4"><div><h2 className="text-xl font-semibold">Equipamentos</h2><p className="text-caption">Ativos vinculados ao seu cadastro e seus dados técnicos.</p></div>{list.loading ? <SkeletonList rows={6}/> : list.error ? <ErrorState error={list.error} onRetry={list.refetch}/> : list.data?.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{list.data.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="portal-card text-left transition hover:border-[var(--color-primary)]/50"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[var(--color-primary)]/10 text-[var(--color-primary)]"><MonitorCog className="h-5 w-5"/></span><Status value={item.status}/></div><h3 className="mt-4 font-semibold">{item.name}</h3><p className="text-caption">{[item.manufacturer,item.model,item.capacity].filter(Boolean).join(' · ') || item.equipmentTypeCatalog?.title || item.type}</p><p className="mt-3 flex items-center gap-2 text-xs text-[var(--color-muted-foreground)]"><MapPin className="h-3.5 w-3.5"/>{item.sector || item.address?.name || 'Local não informado'}</p></button>)}</div> : <EmptyState icon={MonitorCog} title="Nenhum equipamento" description="Os equipamentos cadastrados para você aparecerão aqui."/>}<EquipmentDrawer item={selected} onClose={() => setSelected(null)}/></section>;
}

function CustomerTickets({ onOpenTicket, version }: { onOpenTicket: () => void; version: number }) {
  const [page,setPage] = useState(1); const [selected,setSelected] = useState<CustomerServiceTicket|null>(null);
  const list = useQuery((signal) => customerPortalApi.listMyTickets({ page, limit: 15, signal }), [page, version]);
  return <section className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Meus chamados</h2><p className="text-caption">Acompanhe solicitações e atendimentos gerados.</p></div><button onClick={onOpenTicket} className="btn-primary"><Plus className="h-4 w-4"/>Abrir chamado</button></div>{list.loading && !list.data ? <SkeletonList rows={5}/> : list.error ? <ErrorState error={list.error} onRetry={list.refetch}/> : list.data?.items.length ? <div className="grid gap-3">{list.data.items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="portal-card flex items-center justify-between gap-4 text-left"><div><strong>CH-{String(item.number).padStart(6,'0')} · {item.title}</strong><p className="text-caption">{DOCUMENT_LABEL[item.documentType]} · aberto em {formatDateTime(item.createdAt)}</p></div><Status value={item.status}/></button>)}</div> : <EmptyState icon={TicketCheck} title="Nenhum chamado" description="Use “Abrir chamado” quando precisar de atendimento."/>}{list.data && list.data.pagination.totalPages > 1 && <SimplePager page={page} total={list.data.pagination.totalPages} onChange={setPage}/>}<TicketDetailDrawer item={selected} onClose={() => setSelected(null)}/></section>;
}

function TicketDrawer({ open,onClose,onCreated }: { open:boolean; onClose:()=>void; onCreated:()=>void }) {
  const { session } = useCustomerAuth();
  const equipments = useQuery((signal) => open ? customerPortalApi.listEquipments(signal) : Promise.resolve([]), [open]);
  const [documentType,setDocumentType] = useState<DocumentTemplateType>('WORK_ORDER'); const [addressId,setAddressId] = useState(''); const [equipmentIds,setEquipmentIds] = useState<string[]>([]); const [title,setTitle] = useState(''); const [description,setDescription] = useState(''); const [preferredDate,setPreferredDate] = useState(''); const [busy,setBusy] = useState(false); const [error,setError] = useState<string|null>(null); const [created,setCreated] = useState<CustomerServiceTicket|null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const ticket = await customerPortalApi.createTicket({ documentType, operationType: 'CORRETIVA', addressId: addressId || undefined, equipmentIds, title, description, preferredDate: preferredDate ? new Date(`${preferredDate}T12:00:00`).toISOString() : undefined, contactName: session?.account.name, contactPhone: session?.customer.phone ?? undefined }); setCreated(ticket); onCreated(); } catch(cause) { setError(cause instanceof ApiClientError ? cause.message : 'Não foi possível abrir o chamado.'); } finally { setBusy(false); } }
  function close() { setCreated(null); setDocumentType('WORK_ORDER'); setAddressId(''); setEquipmentIds([]); setTitle(''); setDescription(''); setPreferredDate(''); setError(null); onClose(); }
  return <Drawer open={open} onClose={close} title={created ? 'Chamado enviado' : 'Abrir chamado'} eyebrow="Atendimento" width="max-w-2xl" footer={!created ? <><button type="button" onClick={close} className="btn-secondary">Cancelar</button><button form="customer-ticket-form" disabled={busy} className="btn-primary">{busy ? 'Enviando…' : 'Enviar chamado'}</button></> : <button type="button" onClick={close} className="btn-primary">Concluir</button>}>{created ? <div className="grid min-h-80 place-items-center text-center"><div><TicketCheck className="mx-auto h-12 w-12 text-[var(--color-success)]"/><h3 className="mt-4 text-xl font-semibold">CH-{String(created.number).padStart(6,'0')}</h3><p className="mt-2 text-sm text-[var(--color-muted-foreground)]">Recebemos sua solicitação. Ela já está disponível para a equipe responsável.</p></div></div> : <form id="customer-ticket-form" onSubmit={submit} className="space-y-5">{error && <p className="rounded-md bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]">{error}</p>}<div><h3 className="font-semibold">O que você precisa?</h3><p className="text-caption">Somente assunto e descrição são obrigatórios.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo de atendimento"><select value={documentType} onChange={(e) => setDocumentType(e.target.value as DocumentTemplateType)} className="input w-full">{TICKET_TYPE_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field><Field label="Local (opcional)"><select value={addressId} onChange={(e) => setAddressId(e.target.value)} className="input w-full"><option value="">Definir com a equipe</option>{session?.customer.addresses.map((address) => <option key={address.id} value={address.id}>{address.name} · {address.street}, {address.number}</option>)}</select></Field></div><MultiSelect label="Equipamentos envolvidos (opcional)" value={equipmentIds} onChange={setEquipmentIds} options={(equipments.data ?? []).map((item) => ({ value:item.id,label:[item.manufacturer,item.model,item.capacity].filter(Boolean).join(' - ') || item.name,description:item.sector ?? undefined }))} placeholder="Selecione um ou mais equipamentos"/><Field label="Assunto *"><input required maxLength={160} value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Ex.: Equipamento sem refrigeração" className="input w-full"/></Field><Field label="Descreva a necessidade *"><textarea required minLength={10} maxLength={5000} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Conte brevemente o que está acontecendo e desde quando." className="input min-h-28 w-full py-3"/></Field><Field label="Data preferencial (opcional)"><input type="date" value={preferredDate} onChange={(e) => setPreferredDate(e.target.value)} className="input w-full sm:max-w-xs"/></Field></form>}</Drawer>;
}

function OperationRow({ item }: { item: CustomerPortalOperation }) { const execution = item.pmocExecutionRequest ? `Execução PMOC ${String(item.pmocExecutionRequest.equipmentExecutionNumber).padStart(3,'0')}` : item.rvtExecution ? `Execução RVT ${String(item.rvtExecution.executionNumber).padStart(3,'0')}` : DOCUMENT_LABEL[item.requestedDocumentType]; return <div className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">OP-{String(item.number).padStart(6,'0')} · {execution}</p><p className="truncate text-caption">{item.equipment?.name || item.inspectedEquipments.map((entry) => entry.equipment.name).join(', ') || 'Sem equipamento específico'} · {formatDateTime(item.completedAt || item.scheduledFor || item.createdAt)}</p></div><Status value={item.status}/></div>; }
function OperationDrawer({ item,onClose }: { item:CustomerPortalOperation|null; onClose:()=>void }) { return <Drawer open={Boolean(item)} onClose={onClose} title={item ? `Atendimento OP-${String(item.number).padStart(6,'0')}` : 'Atendimento'} eyebrow={item ? DOCUMENT_LABEL[item.requestedDocumentType] : undefined} width="max-w-2xl">{item && <div className="space-y-5"><div className="flex justify-end"><Status value={item.status}/></div><section className="portal-subcard"><h3 className="font-semibold">Detalhes</h3><dl className="mt-3 space-y-3"><Data label="Solicitação" value={item.reportedIssue}/><Data label="Serviço" value={item.serviceDescription}/><Data label="Observações" value={item.observations}/><Data label="Responsável" value={item.operator.name}/><Data label="Agendamento" value={formatDateTime(item.scheduledFor)}/><Data label="Conclusão" value={formatDateTime(item.completedAt)}/></dl></section><section className="portal-subcard"><h3 className="font-semibold">Equipamentos</h3><div className="mt-3 space-y-2">{(item.inspectedEquipments.length ? item.inspectedEquipments.map((entry) => entry.equipment) : item.equipment ? [item.equipment] : []).map((equipment) => <div key={equipment.id} className="rounded-md bg-[var(--color-muted)]/50 p-3 text-sm"><strong>{equipment.name}</strong><p className="text-caption">{[equipment.manufacturer,equipment.model,equipment.capacity].filter(Boolean).join(' · ') || 'Dados técnicos não informados'}</p></div>)}</div></section>{item.documents.length > 0 && <section className="portal-subcard"><h3 className="font-semibold">Documentos relacionados</h3><div className="mt-3 space-y-2">{item.documents.map((document) => <div key={document.id} className="flex justify-between rounded-md border p-3 text-sm"><span>{document.number} · {DOCUMENT_LABEL[document.type]}</span><Status value={document.status}/></div>)}</div></section>}</div>}</Drawer>; }
function EquipmentDrawer({ item,onClose }: { item:CustomerPortalEquipment|null; onClose:()=>void }) { return <Drawer open={Boolean(item)} onClose={onClose} title={item?.name ?? 'Equipamento'} eyebrow="Equipamento cadastrado">{item && <dl className="space-y-3"><Data label="Tipo" value={item.equipmentTypeCatalog?.title || item.type}/><Data label="Marca" value={item.manufacturer}/><Data label="Modelo" value={item.model}/><Data label="Capacidade" value={item.capacity}/><Data label="Número de série" value={item.serialNumber}/><Data label="Setor" value={item.sector}/><Data label="Tensão" value={item.voltage}/><Data label="Instalação" value={formatDate(item.installationDate)}/><Data label="Garantia até" value={formatDate(item.warrantyExpiration)}/><Data label="Observações" value={item.observations}/></dl>}</Drawer>; }
function TicketDetailDrawer({ item,onClose }: { item:CustomerServiceTicket|null; onClose:()=>void }) { return <Drawer open={Boolean(item)} onClose={onClose} title={item ? `Chamado CH-${String(item.number).padStart(6,'0')}` : 'Chamado'} eyebrow={item?.title}>{item && <div className="space-y-4"><div className="flex justify-end"><Status value={item.status}/></div><dl className="space-y-3"><Data label="Tipo" value={DOCUMENT_LABEL[item.documentType]}/><Data label="Descrição" value={item.description}/><Data label="Local" value={item.address ? `${item.address.street}, ${item.address.number} · ${item.address.city}/${item.address.state}` : null}/><Data label="Data preferencial" value={formatDate(item.preferredDate)}/><Data label="Aberto em" value={formatDateTime(item.createdAt)}/><Data label="Atendimento gerado" value={item.operation ? `OP-${String(item.operation.number).padStart(6,'0')} · ${STATUS_LABEL[item.operation.status]}` : 'Ainda não gerado'}/></dl></div>}</Drawer>; }
function Metric({ icon:Icon,label,value }: { icon:typeof ClipboardList;label:string;value:string }) { return <article className="portal-card"><div className="flex items-center justify-between"><div><p className="text-caption">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-lg bg-[var(--color-primary)]/10 text-[var(--color-primary)]"><Icon className="h-5 w-5"/></span></div></article>; }
function Data({ label,value }: { label:string;value:React.ReactNode }) { return <div className="grid gap-1 sm:grid-cols-[140px_1fr]"><dt className="text-caption">{label}</dt><dd className="text-sm">{value || 'Não informado'}</dd></div>; }
function Status({ value }: { value:string }) { const success = value === 'COMPLETED' || value === 'CLOSED' || value === 'OPERATION_CREATED'; const danger = value === 'CANCELED'; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[11px] font-semibold ${success ? 'bg-[var(--color-success)]/10 text-[var(--color-success)]' : danger ? 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]' : 'bg-[var(--color-warning)]/10 text-[var(--color-warning)]'}`}>{STATUS_LABEL[value] || value}</span>; }
function Field({ label,children }: { label:string;children:React.ReactNode }) { return <label className="block space-y-1.5"><span className="text-sm font-medium">{label}</span>{children}</label>; }
function SimplePager({ page,total,onChange }: { page:number;total:number;onChange:(value:number)=>void }) { return <div className="flex items-center justify-end gap-3"><button disabled={page<=1} onClick={() => onChange(page-1)} className="btn-secondary">Anterior</button><span className="text-caption">Página {page} de {total}</span><button disabled={page>=total} onClick={() => onChange(page+1)} className="btn-secondary">Próxima</button></div>; }
