'use client';

import { useState } from 'react';
import { ClipboardCheck, MessageSquareText, Search, Wrench } from 'lucide-react';
import { PageHeader } from '@platform/components/page-header';
import { DataTable, type Column } from '@platform/components/data-table';
import { Pagination } from '@platform/components/pagination';
import { OperationCreationDrawer } from '@platform/components/operation-creation-drawer';
import { OperationDetailDrawer } from '@platform/components/operation-detail-drawer';
import { Drawer } from '@erp/ui/drawer';
import { EmptyState } from '@erp/ui/empty-state';
import { ErrorState } from '@erp/ui/states';
import { SkeletonList } from '@erp/ui/skeletons';
import { ApiClientError, customerPortalApi, useQuery, type CreateOperationPayload, type CustomerPortalTicketStatus, type CustomerServiceTicket, type OperationDetail } from '@erp/api';
import { formatDateTime } from '@erp/utils';

const STATUS: Record<CustomerPortalTicketStatus, { label:string;tone:string }> = {
  OPEN: { label:'Aberto',tone:'bg-[var(--color-warning)]/10 text-[var(--color-warning)]' },
  IN_REVIEW: { label:'Em análise',tone:'bg-[var(--color-primary)]/10 text-[var(--color-primary)]' },
  OPERATION_CREATED: { label:'Atendimento criado',tone:'bg-[var(--color-success)]/10 text-[var(--color-success)]' },
  CLOSED: { label:'Encerrado',tone:'bg-[var(--color-muted)] text-[var(--color-muted-foreground)]' },
  CANCELED: { label:'Cancelado',tone:'bg-[var(--color-danger)]/10 text-[var(--color-danger)]' },
};
const TYPE: Record<string,string> = { WORK_ORDER:'Ordem de Serviço',TECHNICAL_REPORT:'Visita Técnica',TECHNICAL_OPINION:'Laudo Técnico' };

export default function ServiceTicketsPage() {
  const [page,setPage] = useState(1); const [limit,setLimit] = useState(20); const [search,setSearch] = useState(''); const [status,setStatus] = useState<CustomerPortalTicketStatus|''>('');
  const [selected,setSelected] = useState<CustomerServiceTicket|null>(null); const [prefill,setPrefill] = useState<Partial<CreateOperationPayload>|null>(null); const [operationTicket,setOperationTicket] = useState<CustomerServiceTicket|null>(null); const [operationId,setOperationId] = useState<string|null>(null); const [loadingPrefill,setLoadingPrefill] = useState(false); const [actionError,setActionError] = useState<string|null>(null);
  const list = useQuery((signal) => customerPortalApi.listTickets({ page,limit,search,status:status||undefined,signal }), [page,limit,search,status]);
  const columns: Column<CustomerServiceTicket>[] = [
    { key:'number',header:'Chamado',cell:(item)=><div><strong>CH-{String(item.number).padStart(6,'0')}</strong><p className="text-caption">{TYPE[item.documentType] ?? item.documentType}</p></div> },
    { key:'customer',header:'Cliente',cell:(item)=><div><strong>{item.customer.tradeName || item.customer.name}</strong><p className="text-caption">{item.contactName || item.account.name}</p></div> },
    { key:'title',header:'Solicitação',cell:(item)=><div className="max-w-md"><strong>{item.title}</strong><p className="truncate text-caption">{item.description}</p></div> },
    { key:'date',header:'Abertura',cell:(item)=>formatDateTime(item.createdAt) },
    { key:'status',header:'Status',cell:(item)=><TicketStatus status={item.status}/> },
  ];
  async function openCreation(ticket:CustomerServiceTicket) { setLoadingPrefill(true); setActionError(null); try { setPrefill(await customerPortalApi.getOperationPrefill(ticket.id)); setOperationTicket(ticket); setSelected(null); } catch(cause) { setActionError(cause instanceof ApiClientError ? cause.message : 'Não foi possível preparar o atendimento.'); } finally { setLoadingPrefill(false); } }
  async function submitOperation(payload:CreateOperationPayload):Promise<OperationDetail> { if(!operationTicket) throw new Error('Chamado não selecionado'); return customerPortalApi.createOperation(operationTicket.id,payload); }
  return <div className="max-w-[1500px] space-y-6"><PageHeader eyebrow="Gestão" title="Chamados" description="Solicitações abertas pelos clientes e conversão para o fluxo operacional oficial."/><section className="grid gap-3 sm:grid-cols-3"><Kpi icon={MessageSquareText} label="Total filtrado" value={list.data?.pagination.total ?? 0}/><Kpi icon={ClipboardCheck} label="Abertos nesta página" value={list.data?.items.filter((item)=>item.status==='OPEN').length ?? 0}/><Kpi icon={Wrench} label="Operações geradas" value={list.data?.items.filter((item)=>Boolean(item.operation)).length ?? 0}/></section><section className="space-y-4 rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-4"><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--color-muted-foreground)]"/><input value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar chamado, descrição ou cliente" className="input w-full pl-9"/></label><select value={status} onChange={(e)=>{setStatus(e.target.value as CustomerPortalTicketStatus|'');setPage(1);}} className="input"><option value="">Todos os status</option>{Object.entries(STATUS).map(([value,copy])=><option key={value} value={value}>{copy.label}</option>)}</select></div>{actionError && <p className="rounded-md bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]">{actionError}</p>}{list.loading && !list.data ? <SkeletonList rows={7}/> : list.error ? <ErrorState error={list.error} onRetry={list.refetch}/> : list.data?.items.length ? <><DataTable columns={columns} rows={list.data.items} onRowClick={setSelected}/><Pagination pagination={list.data.pagination} onPageChange={setPage} onPageSizeChange={(value)=>{setLimit(value);setPage(1);}}/></> : <EmptyState icon={MessageSquareText} title="Nenhum chamado encontrado" description="Os chamados abertos no Portal do Cliente aparecerão aqui."/>}</section><TicketDrawer ticket={selected} busy={loadingPrefill} onClose={()=>setSelected(null)} onCreate={openCreation} onOpenOperation={(id)=>{setSelected(null);setOperationId(id);}}/><OperationCreationDrawer open={Boolean(operationTicket && prefill)} mode="operation" initialValues={prefill ?? undefined} lockCustomer contextNotice={operationTicket ? `Dados importados do chamado CH-${String(operationTicket.number).padStart(6,'0')}. Revise e atribua o atendimento.` : undefined} submitOperation={submitOperation} submitLabel="Criar e atribuir atendimento" onClose={()=>{setOperationTicket(null);setPrefill(null);}} onCreated={(operation)=>{setOperationTicket(null);setPrefill(null);setOperationId(operation.id);void list.refetch();}}/><OperationDetailDrawer operationId={operationId} open={Boolean(operationId)} onClose={()=>setOperationId(null)}/></div>;
}

function TicketDrawer({ ticket,busy,onClose,onCreate,onOpenOperation }:{ ticket:CustomerServiceTicket|null;busy:boolean;onClose:()=>void;onCreate:(ticket:CustomerServiceTicket)=>void;onOpenOperation:(id:string)=>void }) { return <Drawer open={Boolean(ticket)} onClose={onClose} title={ticket ? `Chamado CH-${String(ticket.number).padStart(6,'0')}` : 'Chamado'} eyebrow={ticket?.customer.tradeName || ticket?.customer.name} width="max-w-2xl" footer={ticket ? ticket.operation ? <button className="btn-primary" onClick={()=>onOpenOperation(ticket.operation!.id)}>Abrir atendimento</button> : <button disabled={busy} className="btn-primary" onClick={()=>void onCreate(ticket)}>{busy?'Preparando…':'Criar operação e delegar'}</button> : undefined}>{ticket && <div className="space-y-5"><div className="flex justify-end"><TicketStatus status={ticket.status}/></div><section className="portal-subcard"><h3 className="font-semibold">Solicitação</h3><dl className="mt-3 space-y-3"><Data label="Tipo" value={TYPE[ticket.documentType] ?? ticket.documentType}/><Data label="Assunto" value={ticket.title}/><Data label="Descrição" value={ticket.description}/><Data label="Data preferencial" value={formatDateTime(ticket.preferredDate)}/></dl></section><section className="portal-subcard"><h3 className="font-semibold">Cliente e contato</h3><dl className="mt-3 space-y-3"><Data label="Cliente" value={ticket.customer.tradeName || ticket.customer.name}/><Data label="Solicitante" value={ticket.contactName || ticket.account.name}/><Data label="Telefone" value={ticket.contactPhone || ticket.account.phone}/><Data label="E-mail" value={ticket.account.email}/><Data label="Endereço" value={ticket.address ? `${ticket.address.street}, ${ticket.address.number} · ${ticket.address.city}/${ticket.address.state}` : 'A definir'}/></dl></section>{ticket.operation && <section className="portal-subcard"><h3 className="font-semibold">Atendimento vinculado</h3><p className="mt-2 text-sm">OP-{String(ticket.operation.number).padStart(6,'0')} · {ticket.operation.operator.name}</p></section>}</div>}</Drawer>; }
function TicketStatus({status}:{status:CustomerPortalTicketStatus}) { const copy=STATUS[status]; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${copy.tone}`}>{copy.label}</span>; }
function Kpi({icon:Icon,label,value}:{icon:typeof MessageSquareText;label:string;value:number}) { return <article className="portal-card flex items-center justify-between"><div><p className="text-caption">{label}</p><p className="text-2xl font-semibold">{value}</p></div><Icon className="h-5 w-5 text-[var(--color-primary)]"/></article>; }
function Data({label,value}:{label:string;value:React.ReactNode}) { return <div className="grid gap-1 sm:grid-cols-[140px_1fr]"><dt className="text-caption">{label}</dt><dd className="text-sm">{value || 'Não informado'}</dd></div>; }
